# Do a full build, tasks.build already implicitly builds rust
[tasks.build]
dependencies = [
    "format",
    "generate",
    "build-web",
]

# Generate API definitions from proto files
[tasks.generate]
command = "buf"
args = ["generate"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

# Build the web client
[tasks.build-web]
script = [
    "cd examples/web",
    "npm run build",
]

# Run rust web client example
[tasks.example-web]
command = "cargo"
args = ["run", "--example", "grpc_webclient"]

# Generate and open docs in browser
[tasks.doc]
command = "cargo"
args = ["doc", "--no-deps", "--open"]
